--
-- 082: Allow REPETITION_STOPPED task activity event
--

ALTER TABLE public.task_events
  DROP CONSTRAINT IF EXISTS task_events_event_type_check;

ALTER TABLE public.task_events
  ADD CONSTRAINT task_events_event_type_check
  CHECK (event_type = ANY (ARRAY[
    'ACTIVE','MARK_COMPLETE','UNDO_COMPLETE',
    'PROOF_UPLOADED','PROOF_UPLOAD_FAILED_REVERT','PROOF_REMOVED','PROOF_REQUESTED',
    'VOUCHER_ACCEPT','VOUCHER_DENY','VOUCHER_DELETE',
    'RECTIFY','OVERRIDE','DEADLINE_MISSED','VOUCHER_TIMEOUT',
    'POMO_COMPLETED','DEADLINE_WARNING_1H','DEADLINE_WARNING_5M',
    'GOOGLE_EVENT_CANCELLED','POSTPONE','REPETITION_STOPPED',
    'AI_APPROVE','AI_DENY','AI_DENIED_AUTO_HOP',
    'ESCALATE','AI_ESCALATE_TO_HUMAN','ACCEPT_DENIAL'
  ])) NOT VALID;
